version: '3'

services:
  jenkins:
#    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
      - 50001:50000
    healthcheck:
      test: "bash -c 'docker-machine version | grep build'"
      interval: 30s
      timeout: 20s
      retries: 10